[package]
name = "dm2120f22"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "33075a0271a28e8a2965311eedd29e9266e5fe5f"}
=======
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d0507e7be36876e9e2c84a710de50346ef187fd4"}
>>>>>>> 76470cbfcb7d352d841d8ddafad70788d1dda94f
=======
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "313f36d4bf82a0ea51d9faa548c344abaaef1efd"}
>>>>>>> 856a351978b58cd6273d8e036648f784ce0695d8
